---
- name: Create required directories
  file: >
    path={{ item }}
    state=directory
    owner={{ es_user }}
    group={{ es_group }}
  with_items:
    - "{{ es_pid_dir }}"
    - "{{ es_data_dir }}"
    - "{{ es_work_dir }}"
    - "{{ es_log_dir }}"
    - "{{ es_conf_dir }}"
    - "{{ es_plugin_dir }}"

- name: Copy Configuration File
  template: >
    src=elasticsearch.yml.j2
    dest={{ es_conf_dir }}/elasticsearch.yml
    owner={{ es_user }}
    group={{ es_group }}
  notify: Restart elasticsearch

- name: Copy Default File for Instance
  template: >
    src=elasticsearch.j2
    dest={{ es_default_file }}
  notify: Restart elasticsearch

- name: Copy Systemd File for Instance
  template: >
    src=elasticsearch.service.j2
    dest=/usr/lib/systemd/system/elasticsearch.service
  when: ansible_service_mgr == "systemd"
  notify:
    - Reload systemd daemon
    - Restart elasticsearch

- name: Copy Logging.yml File for Instance
  template: >
    src=logging.yml.j2
    dest={{ es_conf_dir }}/logging.yml
    owner={{ es_user }}
    group={{ es_group }}
  notify: Restart elasticsearch
