---
- name: RedHat - Ensure Java is installed
  yum: >
    name={{ es_java }}
  when: ansible_os_family == 'RedHat'

- name: Debian - Ensure Java is installed
  apt: >
    name={{ es_java }}
    update_cache=yes
    force=yes
  when: ansible_os_family == 'Debian'
