---
- name: Ensure libselinux-python on CentOS 6.x
  yum: >
    name=libselinux-python
  when: ( ansible_distribution == "CentOS" ) and ( ansible_distribution_major_version == "6" )

- name: RedHat - add Elasticsearch repo
  template: >
    src=elasticsearch.repo.j2
    dest=/etc/yum.repos.d/elasticsearch-{{ es_major_version }}.repo
  when: es_use_repository

- name: RedHat - Install Elasticsearch
  yum: >
    name=elasticsearch{% if es_version is defined and es_version != ""  %}-{{ es_version }}{% endif %}
  when: es_use_repository
  register: elasticsearch_install

- name: RedHat - Install Elasticsearch from url
  yum: >
    name={% if es_custom_package_url is defined %}{{ es_custom_package_url }}{% else %}{{ es_package_url }}-{{ es_version }}.noarch.rpm{% endif %}
  when: not es_use_repository
  register: elasticsearch_install
