---
- name: template kibana service
  template: >
    src=kibana.service.j2
    dest=/usr/lib/systemd/system/kibana.service
    backup=yes
  notify:
    - reload systemd daemon
    - restart kibana

- name: template kibana config
  template: >
    src=kibana.yml.j2
    dest=/opt/kibana/config/kibana.yml
    backup=yes
    mode=0640
    owner={{ kibana_user }}
    group={{ kibana_group }}
  notify:
    - restart kibana

- name: template kibana service options
  template: >
    src=kibana.j2
    dest=/etc/sysconfig/kibana
    backup=yes
  notify:
    - restart kibana

- name: start and enable kibana
  service: >
    name=kibana
    state=started
    enabled=yes
