---
- name: Debian - Add Elasticsearch apt key
  apt_key: >
    url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state=present

- name: Debian - Add Logstash repository
  apt_repository: >
    repo=deb http://packages.elasticsearch.org/logstash/{{ logstash_major_version }}/debian stable main
    state=present
    update_cache=yes

- name: Debian - Install Logstash
  apt: >
    name=logstash-{{ logstash_version }}
    state=present
