---
- name: RedHat - Add Elasticsearch GPG key
  rpm_key: >
    key=http://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state=present

- name: RedHat - Add Logstash repository
  template: >
    src=logstash.repo.j2
    dest=/etc/yum.repos.d/logstash.repo

- name: RedHat - Install Logstash
  yum: >
    name=logstash-{{ logstash_version }}
    state=present
