---
- name: Ensure Logstash SSL directory exists
  file: >
    path={{ logstash_ssl_dir }}
    state=directory

- name: Copy SSL key and cert
  copy: >
    content={{ lookup('file', item) }}
    dest={{ logstash_ssl_dir }}/{{ item | basename }}
    mode=0640
    owner=logstash
    group=logstash
  with_items:
    - "{{ logstash_ssl_key }}"
    - "{{ logstash_ssl_certificate }}"
  when: item != ""
  notify: Restart logstash
